### ISSUE TITLE
season_play_by_play not loading

### ISSUE THREAD

**Issue by tdevk** [maksimhorowitz/nflscrapR#71]
I tried fetching the pbp data from 2009 and 2010 but this seems not to work for me. While it is mentioned that this function can take a few minutes to run, I don't get any results after waiting (imo) long enough for it to finish. There are no error messages thrown, it just freezes after this output:
```
Loading required package: XML
Loading required package: RCurl
Loading required package: bitops
```

my script:

```
Sys.setenv(LANG = "en")
install.packages('devtools',repos = "http://cran.us.r-project.org")
library(devtools)
devtools::install_github(repo = "maksimhorowitz/nflscrapR")
library(nflscrapR)

pbp_2009 <- season_play_by_play(2009)
pbp_2010 <- season_play_by_play(2010)

library(tidyverse)
pbp_data <- bind_rows(pbp_2009, pbp_2010)
```

**Comment by chrisjkeeney** [comment]
Are you using R-Studio? If in the top right corner of the Console window, there is a stop sign, that means it's still running. 

It takes a while to run, maybe 15-20 minutes per season. Can vary by your computer and internet connection though. But if that red stop sign is there, that means it's still processing.

**Comment by ryurko** [comment]
Please make sure the package is up to date and use the updated functions scrape_season_play_by_play and scrape_json_play_by_play.

**Comment by roBertus31** [comment]
I know that the issue is closed, but I'm having a similar issue. 

I'm just trying to run this command:

`pbp09 <- scrape_season_play_by_play(2009)`

Appears to be running, ie. the stop sign in the upper right of the console in Rstudio is showing. Yet task manager within windows says that the rsession is not using any CPU, and memory usage is also holding steady, and not increasing. 

sessionInfo output:
`R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nflscrapR_1.8.3 magrittr_1.5    nnet_7.3-12    

loaded via a namespace (and not attached):
[1] compiler_3.5.3 tools_3.5.3`

nflscrapR version: 1.8.3
