### ISSUE TITLE
season_play_by_play not working

### ISSUE THREAD

**Issue by thebamoor** [maksimhorowitz/nflscrapR#8]
> library("nflscrapR", lib.loc="/usr/local/lib/R/3.3/site-library")
> nfl15 <- season_play_by_play(2015)
Loading required package: XML
Loading required package: RCurl
Loading required package: bitops
Error in `[<-.POSIXlt`(`*tmp*`, not_same, value = c(1474521300, 1474521300,  : 
  NAs are not allowed in subscripted assignments

**Comment by maksimhorowitz** [comment]
Update the package!

**Comment by thebamoor** [comment]
Already did.

**Comment by thebamoor** [comment]
> devtools::install_github(repo = "maksimhorowitz/nflscrapR", force=TRUE)
Downloading GitHub repo maksimhorowitz/nflscrapR@master
from URL https://api.github.com/repos/maksimhorowitz/nflscrapR/zipball/master
Installing nflscrapR
'/usr/local/Cellar/r/3.3.1_1/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/y2/bxb87xt15w95vslbkf0kwnj80000gn/T/RtmpAXsoSu/devtoolsa1a1d7dc886/maksimhorowitz-nflscrapR-df1fd71'  \
  --library='/usr/local/lib/R/3.3/site-library' --install-tests 

* installing *source* package ‘nflscrapR’ ...
** R
** data
*** moving datasets to lazyload DB
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (nflscrapR)
> library("nflscrapR", lib.loc="/usr/local/lib/R/3.3/site-library")
> nfl14 <- season_play_by_play(2014)
Loading required package: XML
Loading required package: RCurl
Loading required package: bitops
Error in `[<-.POSIXlt`(`*tmp*`, not_same, value = c(1474863300, 1474863300,  : 
  NAs are not allowed in subscripted assignments

**Comment by maksimhorowitz** [comment]
Looking into it now.  Let me get back to you.

**Comment by maksimhorowitz** [comment]
This should be fixed.  The issue was that the NFL added "End of Half" as a
row in the play by play.  This is accounted for now.  Let me know if you
find any issues.

**Comment by thebamoor** [comment]
You whacked that mole.

**Comment by thebamoor** [comment]
Sorry to be a messenger of bad news once again. Ran into different kinds of errors when I tried to download different seasons. Here's my log:

> nfl15 <- season_play_by_play(2015)
Error in file(con, "r") : cannot open the connection
> nfl13 <- season_play_by_play(2013)
Error in fromJSON(content, handler, default.size, depth, allowComments,  : 
  invalid JSON input
> nfl16 <- season_play_by_play(2016)
Error in `[<-.POSIXlt`(`*tmp*`, not_same, value = c(1474949700, 1474949700,  : 
  NAs are not allowed in subscripted assignments

**Comment by maksimhorowitz** [comment]
Hey,

I will address your bugs in order:

1) nfl15 <- season_play_by_play(2015)
Error in file(con, "r") : cannot open the connection

*This happens sometimes I am not sure why*.  *If you run this line again,
it will work. The only thing I can think of is that the NFL blocks your
connection due to overuse. Will look into this more as this answer is
obviously not satisfying...*

2) nfl13 <- season_play_by_play(2013)
Error in fromJSON(content, handler, default.size, depth, allowComments, :

*I did not get this error when I ran this line.  You sometimes will get the
same error in (1) due to overuse, but I ran this line 4 times and it never
threw the error you got.*

3) nfl16 <- season_play_by_play(2016)
Error in [<-.POSIXlt(*tmp*, not_same, value = c(1474949700, 1474949700, :
NAs are not allowed in subscripted assignments

*This is now fixed*.  *This bug was one similar to the one I fixed last
night.  However, there is a second caveat that then arises.  You cannot
scrape all of the 2016 PBP data because some of the games have not been
played.  To counter this, I added a new argument to the season_play_by_play
function.  You can now enter a "Weeks" argument which allows you to specify
the number of weeks of PBP you want to scrape starting from week 1.  So if
you input 3 for 2016, it will scrape the first three weeks of the season.
Make sure to download the package again to update the package.*

I really appreciate you finding these bugs.  Please keep sending them to me
as you find them.

Thanks,

Max

**Comment by maksimhorowitz** [comment]
Did you have a chance to check if your errors were still arising?

**Comment by thebamoor** [comment]
Hey, yeah, it works now. It usually requires 2-4 attempts - I guess due to more people using your package and the season being underway. 

As for entering no. of weeks, you mean like this?

`nfl16 <- season_play_by_play(2016, 3)`

**Comment by maksimhorowitz** [comment]
Yes, just make sure you redownload the package to account for that update.
I have also fixed a number of bugs in the new update.

**Comment by thebamoor** [comment]
I just gave it a try and it worked perfectly.

**Comment by maksimhorowitz** [comment]
Awesome.  Keep me posted on other bugs you come across and I am excited to
hear more about what you are building from this data!

**Comment by thebamoor** [comment]
I will. One of things I'm doing is coming up with a non-black box version of Football Outsiders' DVOA. You probably can where this is going - rank teams on by-play basis after controlling for game situations, among other things.

**Comment by pricejt75** [comment]
Great package!

I have a similar problem w/ the season_player_game (latest = 3f55114):

> players2016 <- season_player_game(Season = 2016)
> Error in file(con, "r") : cannot open the connection

After 5x attempts.

Seems as if it might be related to the above issue for current year for the season_play_by_play function (needing a Weeks parameter)? Strangely, I do not receive the same error for the 2015 season. Is this a bug or misunderstanding (on my part) the limitations of this function?

**Comment by maksimhorowitz** [comment]
Update the package and look at the help documentation, there is a weeks
parameter!  I added it last week.

**Comment by pricejt75** [comment]
I _have_ updated the package (the reason for referencing the GitHub commit hash).

While I see the _Weeks_ parameter of the `season_play_by_play function` mentioned by the OP and addressed by last week's commit, there is no _Weeks_ parameter for the function `season_player_game` I'm inquiring about.

My thinking was that the root issue/fix may be related to this "weeks" issue for current season data and be addressed similarly. Thus, I opted to inquire on this issue/thread rather than start a new one.

**Comment by maksimhorowitz** [comment]
Ah I see.  I misread your first comment hence why I gave those
instructions.  I can add this, as it should not be too difficult.  Stay
posted.

**Comment by maksimhorowitz** [comment]
Please reupdate the package now!  A "Weeks" parameter has been added to the
season_player_game function.

**Comment by pricejt75** [comment]
Awesome, yes, that fixed `season_player_game` for me. Similar issue on `season_games` (or so it seems):

> games16 <- season_games(Season = 2016)
> Error in file(con, "r") : cannot open the connection

and `season_rosters` function now fails on the underlying call to `season_player_game`:

> roster16 <- season_rosters(Season = 2016)
> Error in season_player_game(Season) : 
>   argument "Weeks" is missing, with no default

If these should be separate issues, please let me know... I'm fairly new to the GitHub community and I'm not clear on the etiquette.

Finally, this also might not be the proper venue for the question, but do you know if there's a delay in the data for current season? I was trying Weeks = 4 earlier today on the `season_play_by_play` function, and it wasn't working for me. _Weeks = 3_ seemed fine... but _Weeks = 4_ works for both `season_play_by_play` and the `season_player_game` functions this evening. Not sure if the behavior is anomaly of the source data/API?

**Comment by maksimhorowitz** [comment]
I will add the weeks parameter to season_rosters. And yes the API does have
some lag. I think by at least one day. Let me check the season play by play
function and get back to you.

**Comment by maksimhorowitz** [comment]
I added weeks to both the season_roster and season_games functions.  I also
added, scores to the season_games function.

**Comment by pricejt75** [comment]
Looks good from what I can tell. Thanks.
